name: SimpleSave
main: org.desmin88.simplesave.SimpleSave
version: 3.03
author: desmin88
description: Automatically saves and backups world and player data
commands:
  ssBackup:
    description: Manual Backup
    usage: /ssBackup